### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by addshore** [phar-io/version#26]
I'd love to be able to use https://github.com/phar-io/version/pull/25 asap :)

**Comment by theseer** [comment]
It's likely to be 3.1.0, given we added a new method.

And I'd like to fix #23 first, already working on it.

**Comment by addshore** [comment]
> It's likely to be 3.1.0, given we added a new method.

Sounds good!
I wasn't sure how semver strict this repo was, as I noticed 3.0.3 had a method added but was only a patch release.

**Comment by theseer** [comment]
Yeah, that was probably wrong :see_no_evil: ...

**Comment by theseer** [comment]
Done. All tests are green on my system. Release 3.1.0 is tagged and pushed.
